user_list = [
  {username: "blinded93", email: "blinded93@gmail.com", password: "password"},
  {username: "montiechristo", email: "montiechristo@gmail.com", password: "pw"},
  {username: "klank01", email: "klank01@gmail.com", password: "theendasweknowit"},
  {username: "narcissus", email: "narcissus@gmail.com", password: "narc"},
  {username: "evadiva", email: "evadiva@gmail.com", password: "princess"}
]

user_list.each do |hash|
  User.create(hash)
end

recipe_list = [
  {name: "Vegan Cream Cheese Frosting", ingredients: "1/2 cup vegan butter, 1/2 cup vegan cream cheese, 1/2 tsp pure vanilla extract, 2 cups powdered icing sugar, 1 tsp almond milk or as needed", directions: "In a large bowl, beat the butter, cream cheese, and vanilla together with an electric mixer until smooth.\r\nSlowly add in the powdered icing sugar, a bit at a time, and beat until smooth. Add almond milk, a teaspoon at a time, to thin as desired; beat after each addition. Leftovers can be stored in the fridge in an airtight container for 3 to 5 days.", cook_time: 0, prep_time: 5, servings: 6, skill_level: "Easy", favorite: 0},
  {name: "In the Buff Smoothie Bowl", ingredients: "1 cup almond milk, 1/4 cup packed avocado, 1 large frozen banana, 1 tsp chia seeds, 1 heaping tbsp hemp seeds, 1/4 cup unflavored protein powder, 2 tsp almond butter, 2 pitted Medjool dates, 1/2 tsp cinnamon, 1/4 tsp vanilla extract, 2 ice cubes", directions: "Add 1 cup (250 mL) of almond milk into a high-speed blender, followed by the rest of the ingredients. Blend until smooth. If necessary, add more milk to get the blender going.\r\nPour into a bowl, and add your desired toppings. Serve immediately and enjoy with a spoon!", cook_time: 0, prep_time: 10, servings: 1, skill_level: "Easy", favorite: 0},
  {name: "Cozy Butternut, Sweet Potato and Red Lentil Stew", ingredients: " 2 tbsp olive oil, 1 medium onion (diced), 4 garlic cloves (minced), 3 cups (peeled seeded diced) butternut squash, 1 large sweet potato, 3 cups vegetable broth, 1 can diced tomatoes, 1 can light coconut milk, 1/2 cup dried red lentils, 3 tbsp tomato paste, 2 tsp turmeric, 2 tsp cumin, 1/2 tsp chili powder, 1/4 tsp cayenne pepper, Salt (to taste), Freshly ground pepper (to taste), 3 tsp apple cider vinegar, 1 bunch chard", directions: "To a large pot, add the oil, onion, and garlic. Stir to combine. Increase the heat to medium and sauté for 3 to 5 minutes, until the onion is softened.\r\nAdd the squash and sweet potato and stir to combine. Add a pinch of salt and continue sautéing for a few minutes longer.\r\nAdd the broth, diced tomatoes (with juices), coconut milk, lentils, tomato paste, turmeric, cumin, chili powder, cayenne, salt, and pepper. (If you are spice-shy, feel free to add half the amount to start and increase from there after cooking, to taste.) Stir well to combine.\r\nIncrease heat and bring to a boil. Reduce the heat to medium, stir again, and simmer uncovered for about 30 minutes, stirring occasionally, until the squash and potato are fork-tender. Reduce the heat if necessary.\r\nAdd the apple cider vinegar to taste. Adjust the other seasonings if desired.\r\nOptional step: Using a handheld immersion blender, blend the stew for only 2 to 3 seconds (any more and you’ll blend too much of the veggies). This thickens the broth.\r\nStir in the chard, and cook for another couple minutes until the greens are wilted.\r\nScoop some cooked rice onto the bottom of a bowl and then ladle the stew overtop. Garnish with minced cilantro or parsley and a good dusting of garlic and chili powder, if desired.\r\nLeftovers will keep in the fridge for up to 5 days, and they freeze beautifully too.", cook_time: 30, prep_time: 20, servings: 8, skill_level: "Easy", favorite: 0},
  {name: "Jumbo Chocolate Chunk Cookies", ingredients: "1/2 cup smooth almond butter, 1/4 cup maple syrup, 3 tbsp coconut oil, 1/2 tsp vanilla extract, 1/2 cup rolled oats, 1/4 cup oat flower, 1/4 cup arrowroot flower/starch, 1/4 cup almond flour, 1/2 tsp baking soda, 1/2 tsp sea salt, 2 non-dairy dark chocolate bars", directions: "Preheat the oven to 350°F (180°C) and line a very large (approx. 21 by 15 inch) baking sheet with parchment paper.\r\nIn a large bowl, stir together the wet ingredients (almond butter, maple syrup, oil, and vanilla) until completely smooth.\r\nStir the dry ingredients (oats, oat flour, arrowroot, almond flour, baking soda, and salt) into the wet mixture, one by one, until thoroughly combined. The dough will be a bit wet/oily, but this is normal.\r\nChop the chocolate into small chunks. Set aside 3 tablespoons (for topping the cookie dough later), and stir the rest of the chocolate into the batter until combined.\r\nUsing a large retractable cookie scoop (or simply a spoon and your hands), scoop mounds of dough (about 2 1/2 tablespoons of dough per cookie). Add each onto the baking sheet, about 3 inches apart, as they'll spread a lot while baking.\r\nPress the remaining 3 tablespoons of chocolate onto the tops of the cookie dough mounds, evenly distributed. (Reshape the cookie dough mounds if they flatten a bit.)\r\nBake for 8 to 10 minutes (I prefer 8 1/2 to 9 minutes for gooey and soft cookies), until the cookies are spread out. If you prefer a crispy cookie, bake for about 12 minutes.\r\nCool the cookies directly on the baking sheet for about 5 to 6 minutes. The cookies will be super delicate until they are cooled. Using a spatula, gently transfer each cookie directly onto a cooling rack for another 10 minutes, where they'll firm up even more. (It's normal to have a small amount of oil on the bottom of the cookies due to the almond butter. If this bothers you, simply place them on a couple sheets of paper towel.) Serve and enjoy! Allow the cookies to cool completely before storing.", cook_time: 20, prep_time: 15, servings: 4, skill_level: "Easy", favorite: 0},
  {name: "All Day Glow Green Smoothie", ingredients: "1 cup coconut water, 1/2 cup mango juice, 2 large Granny Smith apples, 2 cups packed red leaf lettuce, 2/3 cup loosely packed fresh parsley, 1/3 cup packed fresh cilantro, 1/2 cup frozen mango chunks, 1/4 cup packed avocado, 4 tsp fresh lemon juice, 2 small pieces peeled fresh turmeric, 6 large ice cubes", directions: "Add the coconut water and mango juice into a (64-ounce) high-speed blender. (If your blender is on the small side, you may want to make a half-batch.)\r\nNow add the rest of the ingredients. Blend on high until super smooth. If you have a Vitamix, use the tamper stick to get things moving. Taste and adjust sweetness if desired. If it's too tart, feel free to add a bit of liquid sweetener.\r\nServe and enjoy! Place any leftovers into an airtight container and store in the fridge for up to 24 hours. I love to enjoy half in the morning, and the other half in the afternoon.", cook_time: 0, prep_time: 10, servings: 1, skill_level: "Easy", favorite: 0}
]

recipe_list.each do |hash|
  Recipe.create(hash)
end
